// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	dicom "github.com/suyashkumar/dicom"

	tag "github.com/suyashkumar/dicom/pkg/tag"
)

// IDicomFile is an autogenerated mock type for the IDicomFile type
type IDicomFile struct {
	mock.Mock
}

// FindByTag provides a mock function with given fields: _a0
func (_m *IDicomFile) FindByTag(_a0 tag.Tag) (string, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for FindByTag")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(tag.Tag) (string, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(tag.Tag) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(tag.Tag) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetData provides a mock function with given fields:
func (_m *IDicomFile) GetData() dicom.Dataset {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetData")
	}

	var r0 dicom.Dataset
	if rf, ok := ret.Get(0).(func() dicom.Dataset); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(dicom.Dataset)
	}

	return r0
}

// GetLocation provides a mock function with given fields:
func (_m *IDicomFile) GetLocation() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLocation")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetName provides a mock function with given fields:
func (_m *IDicomFile) GetName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ParseData provides a mock function with given fields:
func (_m *IDicomFile) ParseData() (dicom.Dataset, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ParseData")
	}

	var r0 dicom.Dataset
	var r1 error
	if rf, ok := ret.Get(0).(func() (dicom.Dataset, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() dicom.Dataset); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(dicom.Dataset)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetData provides a mock function with given fields: data
func (_m *IDicomFile) SetData(data dicom.Dataset) {
	_m.Called(data)
}

// SetLocation provides a mock function with given fields: location
func (_m *IDicomFile) SetLocation(location string) {
	_m.Called(location)
}

// SetName provides a mock function with given fields: name
func (_m *IDicomFile) SetName(name string) {
	_m.Called(name)
}

// NewIDicomFile creates a new instance of IDicomFile. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIDicomFile(t interface {
	mock.TestingT
	Cleanup(func())
}) *IDicomFile {
	mock := &IDicomFile{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
